#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local url_jenkins="http://mirrors.jenkins.io/war/${JENKINS_VERSION}/jenkins.war"
  local fnm_jenkins="jenkins-${JENKINS_VERSION}.war"

  cache curl "$fnm_jenkins" "$url_jenkins"

  mkdir -p "$shome/vendor/jenkins-${JENKINS_VERSION}"
  rsync -ia "${BASEBOX_CACHE}/curl/$fnm_jenkins" "$shome/vendor/jenkins-${JENKINS_VERSION}/jenkins.war"
  ln -nfs "jenkins-${JENKINS_VERSION}" "$shome/vendor/jenkins"
}

bootstrap
