#!/usr/bin/env bash

function _jenkins_profile {
  local shome="${_jenkins_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  JENKINS_VERSION='2.60.1'
}

_jenkins_profile
