#!/usr/bin/env bash

function jenkins_server {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  exec java -jar "$shome/vendor/jenkins.war"
}

jenkins_server "$@"
