#!/usr/bin/env bash

function jenkins_server {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  export JENKINS_ARGS="--prefix=/jenkins"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  case "${1:-}" in
    default)
      shift
      exec java -jar "$shome/vendor/jenkins/jenkins.war" "$@"
      ;;
    *)
      echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
      return 1
      ;;
  esac
}

jenkins_server "$@"
